### ISSUE TITLE
[JOSS] Add unit testing via CI

### ISSUE THREAD

**Issue by faroit** [lockepatton/sonipy#2]
The package comes without automatic unit tests. Since the application is sonification, the only way to test the functionality of this package is to __listen__ to the outputs. As this is hard to reproduce I would strongly encourage to include a few unit tests that produce tones give a short known x/y sequence.

This issue is part of a [https://github.com/openjournals/joss-reviews/issues/2446](JOSS submission review)

**Comment by faroit** [comment]
Update: I didn't saw the test folder being part of the main code folder. I suggest

* moving the test folder to `/tests`
* enable automatic unit testing either via travis, circle.ci or github actions

**Comment by lockepatton** [comment]
I've moved and connected the ./tests files to travis - and the passing badge is now in the README.md. 🎉
