### ISSUE TITLE
[JOSS] documentation

### ISSUE THREAD

**Issue by faroit** [lockepatton/sonipy#4]
From the JOSS review criteria list:

> Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

the core API of this software is not documented in detail. I would suggest to build a sphinx-based (given suitable docstrings) documentation and make this available on either gh-pages or readthedocs.

This issue is part of a [https://github.com/openjournals/joss-reviews/issues/2446](JOSS submission review)

**Comment by benjaminrose** [comment]
This is a fairly simple package with minimal entry points for the end user. There may be something between the current README and a full sphinx-based cite. However, since the functions are already documented with doc-strings, a sphinx-based system may still be the easiest.

**Comment by lockepatton** [comment]
Thanks! I've given sonipy a sphinx based readthedocs webpage [here](https://sonipy.readthedocs.io/en/latest/), and linked it on the sonipy homepage. Code for this is hosted in ./docs

**Comment by faroit** [comment]
👍  looks great!
