### ISSUE TITLE
[JOSS] add community guidelines

### ISSUE THREAD

**Issue by faroit** [lockepatton/sonipy#5]
The JOSS review criteria recommends to add community guidelines: for a) Contribute to the software b) Report issues or problems with the software c) Seek support

The first point is covered in the readme but in general, a `contributing.md` document and issue templates would be great additions.

This issue is part of a [https://github.com/openjournals/joss-reviews/issues/2446](JOSS submission review)

**Comment by lockepatton** [comment]
Thanks for this idea - I've implemented it in the most recent commit. Let me know if you have anything of a similar vein in mind; for now, I'm closing the issue here.
